# Generated by Django 5.0.6 on 2024-07-01 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_remove_healthcarefacility_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_details', models.TextField()),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(limit_choices_to={'facility_type': 'pharmacy'}, on_delete=django.db.models.deletion.CASCADE, to='care.healthcarefacility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
